AWSTemplateFormatVersion: '2010-09-09'
Description: GraphQL API layer (prowe)
Transform: AWS::Serverless-2016-10-31
Resources:
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: appsync.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: prowe-graphql
      AuthenticationType: API_KEY
  ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
      DefinitionS3Location: s3://prowe-deploy-bucket/3de5480efa0f2c05ff426ae972b161ee
Outputs:
  GraphQLUrl:
    Value:
      Fn::GetAtt:
      - GraphQLApi
      - GraphQLUrl
  ApiId:
    Value:
      Fn::GetAtt:
      - GraphQLApi
      - ApiId
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ApiId
