AWSTemplateFormatVersion: "2010-09-09"
Description: GraphQL API layer (prowe)
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: nodejs10.x
Parameters:
  DomainName:
    Type: String
    Default: prowe-graphql.dev.sourceallies.com
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: dev.sourceallies.com
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: !Ref DomainName
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref Api
      Stage: Prod
  Route53:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: "prowe-graphql.dev.sourceallies.com"
      HostedZoneName: "dev.sourceallies.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomainName.DistributionDomainName
        HostedZoneId: !GetAtt ApiDomainName.DistributionHostedZoneId
  GraphQLEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/graphql-handler.handler
      Runtime: nodejs10.x
      Policies:
        - AWSLambdaExecute
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /graphql
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /graphql
            Method: post

Outputs:
  {}