AWSTemplateFormatVersion: "2010-09-09"
Description: Teammate service for GraphQL (prowe)
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TeammatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  CreateTeammateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: create-teammate.handler
      Runtime: nodejs10.x
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TeammatesTable
  CreateTeammateDatasource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !ImportValue prowe-graphql-api-ApiId
      Name: CreateTeammateDatasource
      ServiceRoleArn: !ImportValue prowe-graphql-api-ApiRoleArn
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt CreateTeammateLambda.Arn
  CreateTeammateResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !ImportValue prowe-graphql-api-ApiId
      DataSourceName: !GetAtt CreateTeammateDatasource.Name
      TypeName: Mutation
      FieldName: createTeammate
      RequestMappingTemplateS3Location: ./request-mapping.vm
      ResponseMappingTemplate: |
        $utils.toJson($context.result)

  ListTeammateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: list-teammates.handler
      Runtime: nodejs10.x
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TeammatesTable
  ListTeammatesDatasource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !ImportValue prowe-graphql-api-ApiId
      Name: ListTeammatesDatasource
      ServiceRoleArn: !ImportValue prowe-graphql-api-ApiRoleArn
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ListTeammateLambda.Arn
  ListTeammatesResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !ImportValue prowe-graphql-api-ApiId
      DataSourceName: !GetAtt ListTeammatesDatasource.Name
      TypeName: Query
      FieldName: teammates
      RequestMappingTemplateS3Location: ./request-mapping.vm
      ResponseMappingTemplate: |
        $utils.toJson($context.result)
Outputs: {}